warning_threshold: 1
disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - comment_spacing
  - force_cast
  - empty_count
  - nesting
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
#  - colon
#  - comma
#  - control_statement
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
#included: # paths to include during linting. `--path` is ignored if present.
#  - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Core/CoreTests
  - Authorization/AuthorizationTests
  - Course/CourseTests
  - Dashboard/DashboardTests
  - Discovery/DiscoveryTests
  - Discussion/DiscussionTests
  - Profile/ProfileTests
  - WhatsNew/WhatsNewTests
  - Theme/ThemeTests
  - vendor
  - Core/Core/SwiftGen
  - Authorization/Authorization/SwiftGen
  - Course/Course/SwiftGen
  - Discussion/Discussion/SwiftGen
  - Discovery/Discovery/SwiftGen
  - Dashboard/Dashboard/SwiftGen
  - Profile/Profile/SwiftGen
  - WhatsNew/WhatsNew/SwiftGen
  - Theme/Theme/SwiftGen
#  - Source/ExcludedFile.swift
#  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
#analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
#  - explicit_self

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
#force_cast: warning

force_try: error

line_length: 120
type_body_length: 600
function_body_length: 100

trailing_whitespace:
  ignores_empty_lines: true

file_length:
  warning: 850
  error: 1500
  
function_parameter_count:
  warning: 10
  error: 12

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string
    - iPhone
    - API 

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
